[build]
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200